language: java
jdk:
  - openjdk8

# gradle dependency caching magic
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  # report coverage results to codecov
  - bash <(curl -s https://codecov.io/bash)
